#!/bin/bash

LIGHT_PURPLE="\033[1;35m"
LIGHT_RED="\033[1;31m"
NO_COLOR="\033[0m"

branch=$(git branch | grep \* | cut -d ' ' -f2)
remote_url=$(git config --get remote.origin.url)

echo -e "${LIGHT_RED}PUSH${NO_COLOR} branch ${LIGHT_PURPLE}${branch}${NO_COLOR} to ${LIGHT_PURPLE}${remote_url}${NO_COLOR}? "
read  -n 1 -r < /dev/tty
echo

if [[ $REPLY =~ ^[Yy]$ ]]
then
  exit 0
fi
exit 1
