#!/bin/bash
read -p "You are going to overwrite existing dotfiles, are you sure? y/n: " answer
case $answer in
y)  cp tmux/.t*  ~/ 
    cp vim/.v* ~/
    cp git/.g* ~/
    cp bash/.b* ~/
    cp zsh/.z* ~/
    cp ssh/config ~/.ssh/ 
    cp python/.p* ~/
    cp python/.flake8 ~/.config/
    echo "Regular files overwritten" ;;
n) echo "Ok, bye" ;;
esac
